language: node_js
node_js:
    - 0.10
    - 0.11

matrix:
  allow_failures:
    - node_js: '0.11'

before_install:
  - npm install gulp -g

script:
  - gulp default
  - node cloudcmd test

notifications:
    #webhooks:
        #http://requestb.in/12h5bl71
    email:
        on_success: never
        on_failure: change
